- src/components/Navigation.tsx
fixed #62 
File Changed: Navigation.tsx
before:
after:
> [FEATURE] Implement active tabs in navbar

- src/app/cubes/page.tsx
> fix metrics becoming 0

- src/components/ModalCreate.tsx
- src/components/ModalSolve.tsx
> Modal blur full height

- src/components/Timer.tsx
- src/lib/formatTime.ts
> improves time readability

- src/app/page.tsx
- src/components/SettingsMenu.tsx
fixes issue #75 
before:
https://github.com/bryanlundberg/NexusTimer/assets/103115789/9e8597b9-0262-4ac0-b478-e7056b2e4f99
after:
https://github.com/bryanlundberg/NexusTimer/assets/103115789/4d5248e7-d4c8-4228-a0d9-fd0b7b56f286
> [Enhancement]: Enable Closing Settings by Clicking Outside

- src/components/Timer.tsx
> Spacebar behavior

- src/lib/calcStatistics.ts
fix #80 
https://github.com/bryanlundberg/NexusTimer/assets/36365546/ef39cf0e-f91d-413d-8949-dd2996ae3c47
> lowest time rendering

- package-lock.json
- package.json
- src/components/charts/LineCharter.tsx
Should temporarily fix #55  remain improve layout, but overall required functionality is covered.
> add: new lines chart

- src/app/globals.css
- src/app/page.tsx
- src/components/ManualMode.tsx
- src/lib/convertToMs.ts
> Manual mode

- src/components/ManualMode.tsx
> Fix display status

- src/components/CategoryStatistics.tsx
- src/components/LastActivity.tsx
- src/components/ModalSolve.tsx
- src/components/OverviewPanel.tsx
- src/components/SingleSolveItem.tsx
- src/components/StatisticsPanel.tsx
- src/lib/calcAverageStatistics.ts
- src/lib/calcBestTime.ts
- src/lib/calculateBestAo.ts
- src/lib/getDeviation.ts
- src/lib/getMean.ts
> Format time

- src/components/TableRow.tsx
> Add shortcut to cube selection 

- src/components/OverviewPanel.tsx
> complete missing format time

- package-lock.json
- package.json
> Change to version: v13.5.1

- src/components/charts/LineCharter.tsx
> Resolved list generation issues

- src/components/ModalCreate.tsx
> show error if no name while editing cube

- src/components/ModalCreate.tsx
- src/components/ModalSolve.tsx
- src/components/SingleSolveItem.tsx
- src/store/SolvesStore.ts
> Improving modal accessibility for close actions

- src/components/timer/OverviewPanel.tsx
- src/components/timer/StatisticsPanel.tsx
- src/hooks/useTimerStatistics.ts
- src/lib/calcStatistics.ts
> fix statisctis on main timer

- package-lock.json
- package.json
- src/lib/timer/genScramble.js
This PR enhances the overall logic for generating scrambles and also incorporates scrambles for SQ-1 and Megaminx.
Fix: #56 
**Changes**
Include [Rambow](https://github.com/nickcolley/scrambo)
> add scrambow

- src/translations/global.json
Improve cube-insights Spanish Translation
#130 
**Changes**
* In [src/app/translations](https://github.com/bryanlundberg/NexusTimer/blob/main/src/translations/global.json) changed "Insights del Cubo" to "Aspectos del Cubo" 
- [x ] I have reviewed my code and believe it is ready for merging.
- [x ] I understand that this PR may be subject to review and changes.
- [x ] I agree to abide by the code of conduct and contributing guidelines of this project.
> Improve cube-insights Spanish translation

- src/components/Select.tsx
- src/components/select/SelectOption.tsx
- src/components/stats/CardStatistic.tsx
- src/components/stats/LastActivity.tsx
- src/components/stats/PersonalStatistics.tsx
Improve light theme for selects
> style: light theme for select inputs

- src/components/cubes/CheckboxImage.tsx
- src/components/cubes/Modal.tsx
This PR adds bug to edit only name and not the category.
it is related to issue #121 (Not editable modal options).
**Changes**
It fixes the bug not editable modal option.
> edit only name not category successful

- src/hooks/useModalCube.ts
- src/store/timerStore.ts
Reverts bryanlundberg/NexusTimer#137
> Revert "Reset selected cube after delete"

- src/hooks/useModalCube.ts
- src/store/timerStore.ts
Fix issues from the PR #137 
now correctly annotates the TimerStore type
> (Reopened) Reset selected cube after delete

- src/lib/importDataFromFile.ts
In this I added a error message to show up if someone imported a wrong type of file. 
fixes #125 
- [o] I have reviewed my code and believe it is ready for merging.
- [o] I understand that this PR may be subject to review and changes.
- [o] I agree to abide by the code of conduct and contributing guidelines of this project.
> added alert message if anyone selected wrong type of file

- src/components/solves/ModalSolve.tsx
- src/lib/moveSolve.ts
- src/lib/updateCubeOnList.ts
Add feature to allow archiving a single solve
#123
**Changes**
Add a new button to ModalSolve
Create moveSolve function to move one solve from the selected cube
> Archive unique solves

- src/lib/importDataFromFile.ts
Handle imported/uploaded file data and perform validation for the same.
Addresses #144 
**Changes**
Complete the function `isValidCubesData` which accepts the contents of the uploaded file and performs validation before accepting it. The validation ensures the uploaded data matches the required format and is also type safe at the same time.
I have tested it with as many edge cases as I could think of, if there is something unexpected/breaking behaviour please make sure to revert back so I can look into the same. 😄 
> Implement Logic to Validate Imported Data

- src/components/timer/SolveOptions.tsx
- src/hooks/useTimer.ts
Fix  unintentionally timer start for mobile version touching quick action buttons used to start the timer.
#149 
**Changes**
Prevent touch event propagation
Add touch event to handle quick action buttons
> Fix  unintentionally timer start

- src/components/cubes/CheckboxImage.tsx
- src/components/cubes/Modal.tsx
responsive modal for cubes
#157 
**Changes**
- Flex wrap 
- responsive images sizes
> responsive modal for cubes

- src/components/select/SelectToggleButton.tsx
add icons for select input
#153
**Changes**
Icon added
> Add icons to select input fields

- src/components/timer/ScrambleZone.tsx
Fix the impossibility of scroll a long scramble
#161 
**Changes**
Removed from the clickeable timer elements
> fix: scroll scramble

- package-lock.json
- package.json
- src/components/PreloadSettings.tsx
- src/components/Select.tsx
- src/components/timer/OverviewPanel.tsx
- src/components/timer/StatisticsPanel.tsx
- src/components/timer/Timer.tsx
- src/store/timerStore.ts
Drops a confetti animation after doing a single personal best time.
Highlighted the average time after breaking the old record.
#165 
**Changes**
List the changes made in this PR. This could include new features, bug fixes, improvements, or any other modifications.
single pb
https://github.com/bryanlundberg/NexusTimer/assets/119996547/dbf489ad-2c70-4f38-baca-9a99a95e9fb3
Averages PB
> Add personal best time animations / alerts

- src/components/charts/LineCharter.tsx
- src/components/stats/CategoryStatistics.tsx
- src/lib/getBestTime.ts
Add to category statistics "BestTime" line
Styled a little bit better.
#171 
**Changes**
- Refactor getBestTime function
- Black background for chart
- Line width changed
Before:
After:
> Add to category statistics "BestTime" line

- src/components/timer/StatisticsPanel.tsx
Fix default statistic Ao12
#183 
> fix: default timer statistic ao12

- src/components/timer/HeaderTimer.tsx
- src/components/timer/StatisticsPanel.tsx
- src/components/timer/Timer.tsx
Sync menu settings with app alerts
#185 
> Sync menu settings with app alerts

- src/lib/defaultSettings.ts
Change default app settings
#188 
**Changes**
Change default app settings
> Change default app settings

- src/app/layout.tsx
- src/components/PreloadSettings.tsx
- src/components/timer/HeaderTimer.tsx
- src/components/timer/TimerWidgets.tsx
- src/hooks/useTimer.ts
- src/store/timerStore.ts
hide widgets when timer is "ready"
#196 
https://github.com/bryanlundberg/NexusTimer/assets/119996547/1c3749ad-6593-4cc0-91f6-0341f4a166fe
> hide widgets when timer is "ready"

- src/components/cubes/TableRow.tsx
Clear the previous solution history when changing the selected cube in the cubes section (/cubes).
#208 
> fix: wrong-pb-alert

- src/components/menu-settings/Menu.tsx
- src/components/solves/ModalSolve.tsx
- src/hooks/useClickOutside.ts
- src/hooks/useEscape.ts
- src/hooks/useModalCube.ts
Enhance modals with the accessibility to close pressing ESC
#179 
> feat: add closing modals with ESC

- src/components/PreloadSettings.tsx
- src/components/timer/HeaderTimer.tsx
- src/components/timer/Timer.tsx
- src/components/timer/TimerWidgets.tsx
- src/hooks/useTimer.ts
- src/interfaces/TimerStatus.tsx
- src/store/timerStore.ts
Reworked all logic from old timer making it easier to read and maintain, includes new inspection feature.
#69 
**Checklist to merge**
> feat: new logic for timer (testing)

- src/components/cubes/DeleteModal.tsx
- src/components/cubes/ModalCreate.tsx
- src/components/menu-settings/Menu.tsx
- src/components/solves/ModalSolve.tsx
- src/icons/CloseModal.tsx
Implemented a revised modal overlay background color and standardized the appearance of delete, create, and cancel buttons.
#220 
old:
new:
Add any additional comments, context, or information about this PR.
> style: balance modal bg contrast

- src/components/solves/ModalSolve.tsx
- src/icons/ChevronDown.tsx
- src/icons/ChevronUp.tsx
- src/icons/CubeTransparent.tsx
Fix icon size and improve text distribution
#223 
old: 
new:
> style: icons size

- src/components/charts/LineCharter.tsx
- src/components/stats/CategoryStatistics.tsx
- src/hooks/useMetricsSwitch.ts
Change background color for line chart and integrate new options
#199 
old:
light
dark
new:
light
dark
> improve line chart (cube statistics)

- src/app/solves/page.tsx
- src/components/input-text/InputText.tsx
- src/components/solves/SolvesArea.tsx
- src/hooks/useSolvesPage.ts
- src/lib/searchQuery.ts
Adds functionality to search bar in the solves page
https://github.com/bryanlundberg/NexusTimer/assets/119996547/be087ca5-a2f2-45e9-ba01-7a1131b0c432
Pending includ regExp to validate its a correct query
> Filter solves by query

- src/components/cubes/TableRow.tsx
- src/components/stats/StatisticRow.tsx
- src/components/stats/StatisticsHeader.tsx
alternate odd/even colors in chart
old: 
new:
> style: alternate odd/even colors in chart

- src/app/page.tsx
- src/components/timer/FullscreenOption.tsx
- src/components/timer/HeaderTimer.tsx
- src/components/timer/InteractiveIcon.tsx
- src/hooks/useFullScreen.ts
- src/icons/ExitFullScreen.tsx
- src/icons/FullScreen.tsx
Integrates a button to enter and exit from fullscreen mode in the main timer.
fix: #202 
> feat: add Fullscreen mode

- src/components/cubes/ModalCreate.tsx
- src/hooks/useModalCube.ts
- src/translations/global.json
Addresses duplicate name validation mentioned in #204 
**Changes**
duplicate name validation while creating and editing a cube added. 
> cubename validation feature added

- src/components/timer/HintPanel.tsx
- src/lib/timer/genSolution.ts
resolve incorrect event category handling in hints.
#258 
> refactor: resolve incorrect event category handling in hints.

- src/components/solves/EmptySolves.tsx
- src/components/solves/ModalSolve.tsx
Made the options menu responsive by adding an overflow check.
#247 
**Changes**
Add the check to ModalSolve component
> add responsive options menu

- src/components/timer/HintPanel.tsx
Added a basic cache to prevent redundant solution generation and implemented a rule to skip solution generation while the user is solving, improving component performance.
#260 
> feat: cache hint solutions

- src/app/page.tsx
- src/components/scramble-display/ScrambleDisplay.tsx
- src/components/solves/ModalSolve.tsx
- src/components/timer/OverviewPanel.tsx
- src/components/timer/ScrambleImagePanel.tsx
- src/components/timer/ScrambleModal.tsx
- src/components/timer/StatisticsPanel.tsx
- src/components/timer/TimerWidgets.tsx
- src/interfaces/cubeCollection.ts
- src/lib/getDisplayId.ts
- src/store/timerStore.ts
Adds a zoom in effect for scramble-display
List any related issues or tasks that this PR addresses.
**Changes**
- Modified the triggers for the timer with id="touch," excluding the scramble panel.
- Optimized props for the standard scramble-display component.
- Created a new component to display a larger scramble; click anywhere outside to close it.
https://github.com/bryanlundberg/NexusTimer/assets/119996547/5acad211-a539-47a9-9ccf-a7d66fb03161
Add any additional comments, context, or information about this PR.
> feat: scramble new zoom in effect

- src/app/cubes/page.tsx
- src/components/cubes/CheckboxImage.tsx
- src/hooks/useModalCube.ts
Improve colors for cubes modal and fix visual glitch
#276 
**Changes**
Eliminate the reset state
https://github.com/bryanlundberg/NexusTimer/assets/119996547/4645420e-80e1-4ceb-b21e-2efb34db6f60
> style: Invert contrast <create modal>

- src/components/cubes/TableRow.tsx
- src/components/timer/ManualMode.tsx
- src/hooks/useModalCube.ts
- src/hooks/useTimer.ts
- src/lib/deleteSession.ts
- src/lib/finishSession.ts
- src/lib/moveSolve.ts
- src/lib/updateSolve.ts
Fix vulnerability resetting your cube data
#281 
**Changes**
include all props of cube into save function
after:
https://github.com/bryanlundberg/NexusTimer/assets/119996547/547b1f35-a49c-442d-90a2-20d20c415beb
> fix: reset cube data

- package-lock.json
- src/components/timer/ManualMode.tsx
update UI statistics after adding a new time, update dependecy package
#291 
> fix: update UI statistics after adding a new time

- src/components/timer/InteractiveIcon.tsx
- src/components/timer/ManualMode.tsx
- src/hooks/useMetricsSwitch.ts
- src/lib/const/defaultChartValues.ts
> fix: typo in css classname and variable name

- .gitignore
- package-lock.json
- package.json
- playwright.config.ts
- tests/test-1.spec.ts
- tests/test-2.spec.ts
- tests/test-3.spec.ts
- tests/test-4.spec.ts
- tests/test-5.spec.ts
> test: add some (e2e) cases

- src/hooks/useSolvesPage.ts
Implement a simple update of statistics global state (used to happen only on "manual mode")
#299 
> fix: statistics after finish a session

- package-lock.json
- package.json
- src/app/[locale]/page.tsx
- src/components/menu-settings/Menu.tsx
- src/components/menu-settings/MenuSelectLanguage.tsx
- src/components/timer/FullscreenOption.tsx
- src/components/timer/HeaderTimer.tsx
- src/components/timer/InteractiveIcon.tsx
- src/hooks/useForceHashSettings.ts
- src/navigation.ts
> fix: menu hashing - toggling menu settings

- src/components/solves/ModalSolve.tsx
fix #312 
None
**Changes**
- fix the width and height of icons
- remove solid icons and add outline to the icon.
none
> change the icon size and remove solid icon

- src/components/cubes/DeleteModal.tsx
> fix confirm delete button

- package-lock.json
- package.json
- src/components/cubes/TableRow.tsx
- src/components/solves/ModalSolve.tsx
fix #318 
none
**Changes**
change ModelSave.tsx and Tablerow.tsx
none
> fix locale date format

- src/hooks/usePreloadSettings.ts
> fix: add states to preload useEffect

- src/app/[locale]/cubes/page.tsx
- src/components/cubes/ModalCreate.tsx
> refactor: remove not needed hook

- src/app/[locale]/cubes/page.tsx
- src/app/[locale]/solves/page.tsx
- src/components/Select.tsx
- src/components/cubes/CubesSection.tsx
- src/components/cubes/ModalCreate.tsx
- src/components/cubes/TableRow.tsx
- src/components/input-text/InputText.tsx
- src/components/select/Select.tsx
- src/hooks/useModalCube.ts
- src/hooks/useSolveShare.ts
Includes other minor refactors
> refactor: remove random key generation

- package-lock.json
- package.json
- src/app/[locale]/page.tsx
- src/components/ui/alert-dialog.tsx
Alert users about domain migration, and offer options to back up their data.
#350 
> feat: add dialog to timer page

- src/hooks/useCubes.ts
Add sync for cubes' favorite state when navigating between pages.
#353 
> fix: maintain global state for favorite cubes

- src/app/[locale]/cubes/page.tsx
- src/components/dialogs/dialog-delete-collection/dialog-delete-collection.tsx
- src/components/dialogs/dialog-edit-collection/dialog-edit-collection.tsx
- src/hooks/useErrorDialog.ts
- src/hooks/useErrorReset.ts
fixed persistence error in edit and dialog.
none
**Changes**
List the changes made in this PR. This could include new features, bug fixes, improvements, or any other modifications.
reset setError.
none
none
> fix/dialog errors in edit/delete

- messages/bn.json
- messages/cs.json
- messages/de.json
- messages/en.json
- messages/es.json
- messages/et.json
- messages/fi.json
- messages/fr.json
- messages/hi.json
- messages/hu.json
- messages/id.json
- messages/it.json
- messages/ja.json
- messages/ko.json
- messages/ms.json
- messages/nl.json
- messages/no.json
- messages/pl.json
- messages/pt.json
- messages/ro.json
- messages/ru.json
- messages/sk.json
- messages/sv.json
- messages/tr.json
- messages/uk.json
- messages/vi.json
- messages/zh.json
- src/components/MainCubeSelector.tsx
Add favorite cubes for quick access in the main cube selector. (include the translations).
> feat: favorite cubes added as options in the main selector

- src/components/menu-solve-options/menu-solve-options.tsx
- src/hooks/useTimer.ts
Fix quick action buttons for mobile users
#366 
> fix: touch events on timer

- .vscode/settings.json
- e2e/create-new-collection.spec.ts
- e2e/delete-cube-collection.spec.ts
- e2e/edit-cube-collection.spec.ts
- package.json
- src/app/page.tsx
- src/components/navigation/buttons/button-select-mode.tsx
- src/components/navigation/navigation.tsx
- src/components/stackmat.tsx
- src/components/timer/MainTimer.tsx
- src/components/timer/Timer.tsx
- src/components/timer/display/display-container.tsx
- src/components/timer/display/display-time.tsx
- src/hooks/useTimer.ts
- src/store/timerStore.ts
- tsconfig.json
- yarn.lock
Add stackmat and other minor refactors
#374 
> feat: add stackmat

- src/components/cubes/cubes-table.tsx
Change checkbox input for a heart icon.
new: 
old: 
new:
> style: change favorite input

- src/components/dialogs/dialog-enter-new-scramble/dialog-enter-new-scramble.tsx
- src/components/drawners/drawer-hint-panel.tsx
- src/components/timer/ScrambleZone.tsx
Change the UI for scramble zone options
#371 
new:
old:
> refactor scramble zone 

- src/app/settings/options/page.tsx
- src/components/dialogs/dialog-import-backup/dialog-import-backup.tsx
- src/components/menu-settings/DataImportExport.tsx
- src/components/menu-settings/ImportModal.tsx
- src/hooks/useTimer.ts
- src/store/SettingsModalStore.ts
fixed a styling problem that keeps happening when you click on 'settings/import from file' in light mode. stylings changed to drop blur instead of white and black with an opacity of %10
The import screen dialog background is now blurry
Issue #383 
Light Mode:
Dark Mode:
> Updated styling for Import Modal

- src/app/cubes/page.tsx
- src/app/stats/page.tsx
Change position of the overflow bar in cubes & stats pages.
#386 
> style: change position of the overflow bar

- src/components/timer/HintPanel.tsx
- src/components/timer/OverviewPanel.tsx
- src/components/timer/ScrambleImagePanel.tsx
- src/components/timer/ScrambleModal.tsx
- src/components/timer/StatisticsPanel.tsx
- src/components/timer/TimerWidgets.tsx
Simplified logic across timer panels by reducing conditional rendering and duplications. Introduced reusable helper functions for better readability and maintainability. Minor adjustments made to adhere to consistency in coding style.
> refactor: timer components for cleaner and reusable code

- src/app/cubes/page.tsx
- src/components/cubes/cubes-cards.tsx
- src/components/ui/card.tsx
- src/components/ui/chart.tsx
This PR introduces a card-based layout for displaying cubes, improves the usage of hooks by updating dependencies, and adds a customizable charting component for better UI visualization. It also includes minor bug fixes for HTML semantics.
**Changes**
- Added `CubesCards` component for displaying cube information with usage graphs and actions.
- Replaced the previous table-based `CubesTable` view with the new card-based layout for better UX/UI.
- Introduced a new `Chart` component to handle customizable charting needs.
- Updated dependency array in `useEffect` to include `locale` for correct re-renders.
- Switched from `<p>` to `<div>` inside the `Card` component for semantic and functional consistency.
**By submitting this …
> feat: Update cube display and improve charting components

- src/hooks/useEventHandlers.ts
- src/hooks/useHoldToStart.ts
- src/hooks/useInspection.ts
- src/hooks/useSolveData.ts
- src/hooks/useTimer.ts
- src/hooks/useTimerControls.ts
> refactor: core timer logic to enhance coder reusability

- package.json
- pnpm-lock.yaml
- src/components/charts/LineCharter.tsx
- Updated Lightweight Charts dependency from v4 to v5.
- Removed Lightweight logo from chart.
> build: updated lightweight-charts to v5

- src/app/layout.tsx
- src/components/loader/loader-context.tsx
- src/components/loader/ntloader.tsx
- src/store/InitialLoader.ts
Add a first loading screen
Add any additional comments, context, or information about this PR.
> feat: add custom application first loading screen

- src/components/PreloadSettings.tsx
- src/components/charts/LineCharter.tsx
- src/components/dialogs/dialog-edit-collection/dialog-edit-collection.tsx
- src/components/headless/Toggle.tsx
- src/components/menu-settings/MenuOption.tsx
- src/components/menu-settings/MenuSelectDefaultStartCube.tsx
- src/components/menu-settings/ThemeSelect.tsx
- src/components/navigation/buttons/button-navbar.tsx
- src/hooks/usePreloadSettings.ts
- src/interfaces/Settings.ts
- src/lib/const/defaultSettings.ts
- src/lib/loadSettings.ts
- src/lib/settingsUtils.ts
Includes a series of refactors to remove unused code, simplify component logic for settings management. It also introduces utility functions for consistent handling of settings.
> refactor: settings management

- src/components/drawners/drawner-create-collection/drawner-create-collection.tsx
Updated type definitions to use Readonly and streamlined cube validation by removing redundant checks. Also fixed missing dependency in the reset useEffect dependency array for consistency.
#433 
> refactor: simplify type definitions and cube validation logic

- src/components/HeavyWebWorkers.tsx
- src/components/providers.tsx
- src/components/stackmat.tsx
- src/components/stats/CategoryStatistics.tsx
- src/components/timer/ManualMode.tsx
- src/hooks/useMetricsSwitch.ts
- src/hooks/useSolveActions.ts
- src/hooks/useSolveData.ts
- src/store/timerStore.ts
- src/worker/deep-statistics.worker.ts
- src/worker/timer-stats.worker.ts
- tsconfig.json
This PR introduces a Web Worker to offload heavy statistical calculations from the main thread. By moving these computations into a separate worker, the UI remains responsive and overall performance is improved, especially when handling large datasets.
> perf: add web worker for heavy statistical calculations

- package.json
- pnpm-lock.yaml
- src/app/(core-timer)/stats/page.tsx
- src/components/charts/BarCharter.tsx
- src/components/charts/LineCharter.tsx
- src/components/charts/PieCharter.tsx
- src/components/stats/CategoryCharts.tsx
- src/components/stats/CategoryStatistics.tsx
- src/components/stats/DateRangeSelect.tsx
- src/components/stats/StatsSummaryCards.tsx
- src/components/ui/chart.tsx
- src/constants/states.ts
- src/enums/DateRange.ts
- src/hooks/useMetricsSwitch.ts
> feat: extends timer statistics

- src/actions/actions.ts
- src/app/(community)/leaderboards/page.tsx
- src/app/api/v1/leaderboards/route.ts
- src/components/app-sidebar.tsx
- src/components/modals/leaderboard-solve-modal.tsx
- src/components/timer/TimerVirtual.tsx
- src/components/ui/spinner.tsx
- src/hooks/api/useLeaderboards.ts
- src/hooks/useLeaderboardSolveModal.ts
- src/lib/calcTurnsPerSecond.ts
- src/models/solve.ts
- src/store/LeaderboardSolveModal.ts
After completing virtual solves, the information is now sent to the server to be saved and displayed in a ranking of the top 100 solves in history. It only includes virtual solves, since other types could be easily cheated.
#456 
soon will be added more categories, currently is only for 3x3 with keyboard
> feat: ranking system for virtual solves
