- src/components/ManualMode.tsx
fix #91 
input type `number` was causing unexpected behavior to handle minus sign so change input type to `text` for better input control
> add input validation for positive numbers

- src/hooks/useModalCube.ts
- src/store/timerStore.ts
Reset the selected cube to null when it is deleted
#129
**Changes**
useTimerStore was updated to handle null arguments on `setSelectedCube()` and `setNewScramble()`
useModalCube was updated to call these methods on delete if the deleted cube is the selected one
> Reset selected cube after delete

- src/lib/cubeCollection.ts
- src/lib/timer/genScramble.js
Fix scrambles for 333 OH
#140 
**Changes**
- Id "333 OH" is not supported by library, changed to just 333
- Improved a little bit error handler
> fix scramble generator for 333oh category

- src/components/solves/ModalSolve.tsx
improve modal solve for mobile size
#155 
**Changes**
- Time text bold
- Modal centered
- Buttons centered
- Add calendary icon
- Add hh/mm time to modal
before: 
after:
> improve modal solve for mobile size

- src/components/charts/LineCharter.tsx
This PR adds a mean time line to the lineal graph and removes the last time line for the same.
Resolves issue #168 
**Changes**
- Finds average of the times in the displayed
- Adds a line in the graph denoted as mean time with the above average value
- Removes an existing line which showed the last time
> Highlight mean time in lineal graph instead of last time.

- src/components/solves/ModalSolve.tsx
- src/components/solves/SingleSolveItem.tsx
- src/components/timer/Timer.tsx
Changed font size for second half of time display by using .split(".") and wrapping in separate span tags
Minor visual enhancement where the solve time's decimal component is a smaller font size.
None
**Changes**
Used the split function to separate the time string and rendered each part in different span tags with a different font size. This is applied on 3 different places, the solve modal, the grid view and the main Timer.tsx file. 
I haven't thoroughly tested this yet so would like some feedback and expect some adjustments.
- [*] I have reviewed my code and believe it is ready for merging.
- [*] I understand that this PR may be subject to review and changes.
- [*] I agree …
> Font size for time display

- src/components/menu-settings/DataImportExport.tsx
- src/components/menu-settings/Menu.tsx
Update the available new cube list after each import.
#192 
**Changes**
Redirect to the /cubes page during import
Otimize language inheritance 
> fix: sync cubes after import

- src/app/solves/page.tsx
- src/components/button/Button.tsx
- src/components/button/ButtonContainer.tsx
- src/hooks/useSolvesPage.ts
I have addressed the issue #222 
**Changes**
Disabled the button when no cube is selected from the select list in the solves page.
If your PR includes visual changes, provide screenshots or GIFs to demonstrate the ![btn_fix](https://github.com/bryanlundberg/NexusTimer/assets/78807238/6e6141dd-76f0-4499-8acd-6cf4123c3fcb).
> disabled buttons when cube is not selected

- src/lib/calculateBestAo.ts
- src/lib/calculateCurrentAo.ts
- src/lib/getDeviation.ts
Updated formulas in bestAo, currentAo, and getDeviation
#194 
> Fix: Updated formulas in bestAo, currentAo, and getDeviation

- src/components/timer/TimerWidgets.tsx
Fix detect release to start timer on tap, hot fix for mobile users.
#229 
**Changes**
Due to the removal of the UI component when it was ready, the timer lost the reference for the stop-holding event. Instead, it was changed to be hidden with CSS.
> fix: detect release to start timer on tap

- src/components/timer/ManualMode.tsx
- src/lib/getSolvesMetrics.ts
Fix order solves in chart by date
before:
after:
> fix: order solves in chart by date

- .vscode/settings.json
- src/app/solves/page.tsx
- src/components/Select.tsx
- src/components/cubes/TableRow.tsx
- src/components/menu-settings/ImportModal.tsx
- src/components/timer/OverviewPanel.tsx
- src/components/timer/StatisticsPanel.tsx
- src/hooks/useModalCube.ts
- src/lib/calculateBestAo.ts
- Fixes the calculation of the AoX records by adding logic to remove the best and worst times before calculating the average in the current interval.
- Synchronize the statistics of the selected cube from all possible ways that offers a change cube option.
- Adds some `data-testid` attributes as the purpose of this PR started to add more test. 🙄
> refine AoX calculation and include test attributes

- package-lock.json
- package.json
- src/components/charts/LineCharter.tsx
Correct the error: when you zoomed in excessively, you started to see the scale in negative numbers. This was fixed by disabling auto-scaling on the Y-axis. Additionally, the kinetic effect was added for the desktop version when scrolling with the graph, disabled bold labels, added watermark.
#201 
> fix: zoom and scrolling statistics-chart

- src/hooks/useInitializeHint.ts
- src/worker/solver333Worker.js
the initialization of the 333 cross & xcross solver was blocking the UI thread. By offloading the initialization process to a web worker, we ensure that the UI remains responsive during this operation.
issue: (interface respond until finish initializing process)
https://github.com/bryanlundberg/NexusTimer/assets/119996547/5754416e-fbc2-4f11-a170-4e1ea10fac9b
after: (interface keeps responsive while initializing process) [simulate 5 sec delay loading]
https://github.com/bryanlundberg/NexusTimer/assets/119996547/cb0da77a-c2ad-45a4-9d72-3289ac94b18f
**Changes**
- Implemented a web worker to handle the initialization of the 333 solver.
- Modified the hook to interact with the web worker and update the initializing state based on the worker's messages.
**By submitting …
> fix: prevent UI blocking during 333 solver initialization

- src/components/solves/SolvesArea.tsx
remove the border on clicked item, after modal closes
Before:
https://github.com/bryanlundberg/NexusTimer/assets/119996547/489c5faa-b7ec-4d70-91b8-e5568a038cc9
after:
https://github.com/bryanlundberg/NexusTimer/assets/119996547/6cc4bc93-0801-4069-9ce3-0b1159736f1a
> style: remove the visual reference "active" on closed modal

- src/components/dialogs/dialog-edit-collection/dialog-edit-collection.tsx
Se agregó una condición mas al if que valida el nuevo nombre ingresado via edit.
Si el nombre ingresado via edit es igual al nombre actual del cubo, entonces sabemos que el nombre no esta presente en la lista de cubos. (no hace falta ni revisar la lista)
https://github.com/bryanlundberg/NexusTimer/issues/343
**Changes**
- Bug Fix: En https://www.nexustimer.pro/cubes, al editar un cubo, al cambiar el tipo de cubo, obliga a cambiar el nombre del cubo.
- [x ] I have reviewed my code and believe it is ready for merging.
- [x ] I understand that this PR may be subject to review and changes.
- [x ] I agree to abide by the code of conduct and contributing guidelines of this project.
> Cube name validation error when editing Cube, fixed.

- src/components/cubes/cubes-table.tsx
Replaced dropdown with separate buttons due to state management issues in the Radix library when using a dropdown that triggers a dialog.
#352 
Shadcn issue related: https://github.com/shadcn-ui/ui/issues/1912
> refactor: replace dropdown with separate buttons

- src/components/navbar/NavItem.tsx
- src/components/timer/InteractiveIcon.tsx
Adjusted the hover area for displaying the tooltip. Previously, the tooltip was only triggered when hovering over the icon. Now, it activates when hovering over the entire button area, enhancing usability and interaction.
> style: adjust hover area for tooltip

- src/components/timer/Timer.tsx
- src/hooks/useEventHandlers.ts
- src/hooks/useHoldToStart.ts
- src/hooks/useInspection.ts
- src/hooks/useSolveData.ts
- src/hooks/useTimer.ts
- src/hooks/useTimerControls.ts
Refactored the timer core logic to make it more modular. Instead of using Zustand store values directly inside the core, it now takes them as props. This makes it easier to reuse the timer in different modes. (Coming clash mode).
Also replaced `Date.now()` with `performance.now()` for more accurate and consistent timing.
> refactor: improve modularity of timer core logic

- src/app/settings/account/load/page.tsx
- src/app/settings/account/save/page.tsx
- src/components/navigation/navigation.tsx
- src/hooks/useWebsiteColors.ts
Adds `generateDarkTheme ` to create dark themes from a light base using OKLCH.
It parses the primary color, extracts hue and chroma, and generates variants (very dark, dark, medium) to build a consistent dark palette. Fallback values are included for unsupported formats.
> feat: generate dynamic color schemes

- src/components/menu-settings/CustomTheme.tsx
- src/components/menu-settings/ThemeSelect.tsx
- src/models/indexdb/Images.ts
- src/store/BackgroundThemeStore.ts
Migrates background image storage from localStorage to IndexedDB using a custom zustand storage adapter. This allows for better handling of high-quality image uploads without hitting localStorage limits.
Closes #412
**Changes**
- Replaced localStorage with IndexedDB for background image persistence.
- Implemented a custom zustand storage adapter using BoxDB for structured data handling.
No
> feat: move bg image storage from localStorage to IndexedDB

- src/components/timer/ManualMode.tsx
Added a new section to show the last solve time in ManualMode. This improves user visibility of their most recent solve, enhancing the overall user experience.
#430 
**Changes**
List the changes made in this PR. This could include new features, bug fixes, improvements, or any other modifications.
> feat(timer): display last solve time in ManualMode

- src/components/stats/CategoryStatistics.tsx
Makes statistics correctly calculated for each cube individually, because previously they were combined between per cube and global.
> fix: update overall statistics to use cubeAll metrics
